### ISSUE TITLE
Build scripts 

### ISSUE THREAD

**Issue by wardzacharyj** [NamelessIDE/nameless#1]
### Description

Build scripts fails on web.

### Steps to reproduce
From the root directory

1. `npm i`
2. `npm run build-all`

### Relevant Enviroment

Node: `v9.10.1`
npm: `5.8.0`

### Output

```
> @ build-all /Users/Zach/nameless
> lerna exec --parallel --stream -- 'DIRNAME=$(pwd | grep -Po "[^/]+$") && cd .. && npm run build-$DIRNAME'

lerna info version 2.9.1
lerna info exec in 4 package(s): DIRNAME=$(pwd | grep -Po "[^/]+$") && cd .. && npm run build-$DIRNAME
@nameless/cli: > @ build-cli /Users/Zach/nameless
@nameless/cli: > babel -s true packages/cli/src --out-dir packages/cli/dist
@nameless/common: > @ build-common /Users/Zach/nameless
@nameless/common: > babel -s true packages/common/src --out-dir packages/common/dist
@nameless/web: > @ build-web /Users/Zach/nameless
@nameless/web: > NODE_ENV=production webpack --config packages/web/webpack.config.babel.js
@nameless/server: > @ build-server /Users/Zach/nameless
@nameless/server: > babel -s true packages/server/src --out-dir packages/server/dist
@nameless/common: packages/common/src/Event.js -> packages/common/dist/Event.js
@nameless/cli: packages/cli/src/index.js -> packages/cli/dist/index.js
@nameless/common: packages/common/src/index.js -> packages/common/dist/index.js
@nameless/server: packages/server/src/Project.js -> packages/server/dist/Project.js
@nameless/server: packages/server/src/Server.js -> packages/server/dist/Server.js
@nameless/server: packages/server/src/extensions/CMake.js -> packages/server/dist/extensions/CMake.js
@nameless/server: packages/server/src/extensions/Extension.js -> packages/server/dist/extensions/Extension.js
@nameless/server: packages/server/src/extensions/NPM/NPM.js -> packages/server/dist/extensions/NPM/NPM.js
@nameless/server: packages/server/src/extensions/NPM/PackageFile.js -> packages/server/dist/extensions/NPM/PackageFile.js
@nameless/server: packages/server/src/extensions/NPM/index.js -> packages/server/dist/extensions/NPM/index.js
@nameless/server: packages/server/src/extensions/index.js -> packages/server/dist/extensions/index.js
@nameless/server: packages/server/src/index.js -> packages/server/dist/index.js
@nameless/server: packages/server/src/utils/File.js -> packages/server/dist/utils/File.js
@nameless/web: Hash: f69af62842e3eb180b09
@nameless/web: Version: webpack 4.4.1
@nameless/web: Time: 1859ms
@nameless/web: Built at: 2018-3-31 11:56:49
@nameless/web:  4 assets
@nameless/web: Entrypoint index = index.js index.map
@nameless/web: Entrypoint react = react.js react.map
@nameless/web:   [10] ./packages/web/src/index.js + 3 modules 2.25 KiB {1} [built]
@nameless/web:        | ./packages/web/src/index.js 202 bytes [built]
@nameless/web:        | ./packages/web/src/Connection.js 774 bytes [built]
@nameless/web:        | ./packages/web/src/EventWatcher.js 1.13 KiB [built]
@nameless/web:        |     + 1 hidden module
@nameless/web:   [11] multi react react-dom react-router react-hot-loader 64 bytes {0} [built]
@nameless/web:   [12] (webpack)/buildin/harmony-module.js 597 bytes {1} [built]
@nameless/web:   [13] multi ./packages/web/src/index.js 28 bytes {1} [built]
@nameless/web:     + 10 hidden modules
@nameless/web: ERROR in ./packages/web/src/Connection.js
@nameless/web: Module not found: Error: Can't resolve '@nameless/common' in '/Users/Zach/nameless/packages/web/src'
@nameless/web:  @ ./packages/web/src/Connection.js 3:0-57 16:76-97
@nameless/web:  @ ./packages/web/src/index.js
@nameless/web:  @ multi ./packages/web/src/index.js
@nameless/web: ERROR in multi react react-dom react-router react-hot-loader
@nameless/web: Module not found: Error: Can't resolve 'react-dom' in '/Users/Zach/nameless'
@nameless/web:  @ multi react react-dom react-router react-hot-loader
@nameless/web: ERROR in ./packages/web/src/index.js
@nameless/web: Module not found: Error: Can't resolve 'react-dom' in '/Users/Zach/nameless/packages/web/src'
@nameless/web:  @ ./packages/web/src/index.js 5:0-33 7:0-8
@nameless/web:  @ multi ./packages/web/src/index.js
@nameless/web: ERROR in multi react react-dom react-router react-hot-loader
@nameless/web: Module not found: Error: Can't resolve 'react-router' in '/Users/Zach/nameless'
@nameless/web:  @ multi react react-dom react-router react-hot-loader
@nameless/web: Child html-webpack-plugin for "index.html":
@nameless/web:      1 asset
@nameless/web:     Entrypoint undefined = index.html
@nameless/web:        [0] ./node_modules/html-webpack-plugin/lib/loader.js!./packages/web/index.html 637 bytes {0} [built]
@nameless/web: npm ERR! code ELIFECYCLE
@nameless/web: npm ERR! errno 2
@nameless/web: npm ERR! @ build-web: `NODE_ENV=production webpack --config packages/web/webpack.config.babel.js`
@nameless/web: npm ERR! Exit status 2
@nameless/web: npm ERR!
@nameless/web: npm ERR! Failed at the @ build-web script.
@nameless/web: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@nameless/web: npm ERR! A complete log of this run can be found in:
@nameless/web: npm ERR!     /Users/Zach/.npm/_logs/2018-03-31T15_56_50_209Z-debug.log
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: DIRNAME=$(pwd | grep -Po "[^/]+$") && cd .. && npm run build-$DIRNAME
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 2
lerna ERR! npm ERR! @ build-web: `NODE_ENV=production webpack --config packages/web/webpack.config.babel.js`
lerna ERR! npm ERR! Exit status 2
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the @ build-web script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/Zach/.npm/_logs/2018-03-31T15_56_50_209Z-debug.log
lerna ERR!
lerna ERR!
lerna ERR! > @ build-web /Users/Zach/nameless
lerna ERR! > NODE_ENV=production webpack --config packages/web/webpack.config.babel.js
lerna ERR!
lerna ERR! Hash: f69af62842e3eb180b09
lerna ERR! Version: webpack 4.4.1
lerna ERR! Time: 1859ms
lerna ERR! Built at: 2018-3-31 11:56:49
lerna ERR!  4 assets
lerna ERR! Entrypoint index = index.js index.map
lerna ERR! Entrypoint react = react.js react.map
lerna ERR!   [10] ./packages/web/src/index.js + 3 modules 2.25 KiB {1} [built]
lerna ERR!        | ./packages/web/src/index.js 202 bytes [built]
lerna ERR!        | ./packages/web/src/Connection.js 774 bytes [built]
lerna ERR!        | ./packages/web/src/EventWatcher.js 1.13 KiB [built]
lerna ERR!        |     + 1 hidden module
lerna ERR!   [11] multi react react-dom react-router react-hot-loader 64 bytes {0} [built]
lerna ERR!   [12] (webpack)/buildin/harmony-module.js 597 bytes {1} [built]
lerna ERR!   [13] multi ./packages/web/src/index.js 28 bytes {1} [built]
lerna ERR!     + 10 hidden modules
lerna ERR!
lerna ERR! ERROR in ./packages/web/src/Connection.js
lerna ERR! Module not found: Error: Can't resolve '@nameless/common' in '/Users/Zach/nameless/packages/web/src'
lerna ERR!  @ ./packages/web/src/Connection.js 3:0-57 16:76-97
lerna ERR!  @ ./packages/web/src/index.js
lerna ERR!  @ multi ./packages/web/src/index.js
lerna ERR!
lerna ERR! ERROR in multi react react-dom react-router react-hot-loader
lerna ERR! Module not found: Error: Can't resolve 'react-dom' in '/Users/Zach/nameless'
lerna ERR!  @ multi react react-dom react-router react-hot-loader
lerna ERR!
lerna ERR! ERROR in ./packages/web/src/index.js
lerna ERR! Module not found: Error: Can't resolve 'react-dom' in '/Users/Zach/nameless/packages/web/src'
lerna ERR!  @ ./packages/web/src/index.js 5:0-33 7:0-8
lerna ERR!  @ multi ./packages/web/src/index.js
lerna ERR!
lerna ERR! ERROR in multi react react-dom react-router react-hot-loader
lerna ERR! Module not found: Error: Can't resolve 'react-router' in '/Users/Zach/nameless'
lerna ERR!  @ multi react react-dom react-router react-hot-loader
lerna ERR! Child html-webpack-plugin for "index.html":
lerna ERR!      1 asset
lerna ERR!     Entrypoint undefined = index.html
lerna ERR!        [0] ./node_modules/html-webpack-plugin/lib/loader.js!./packages/web/index.html 637 bytes {0} [built]
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/Users/Zach/nameless/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: DIRNAME=$(pwd | grep -Po "[^/]+$") && cd .. && npm run build-$DIRNAME
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ build-web: `NODE_ENV=production webpack --config packages/web/webpack.config.babel.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ build-web script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Zach/.npm/_logs/2018-03-31T15_56_50_209Z-debug.log


> @ build-web /Users/Zach/nameless
> NODE_ENV=production webpack --config packages/web/webpack.config.babel.js

Hash: f69af62842e3eb180b09
Version: webpack 4.4.1
Time: 1859ms
Built at: 2018-3-31 11:56:49
 4 assets
Entrypoint index = index.js index.map
Entrypoint react = react.js react.map
  [10] ./packages/web/src/index.js + 3 modules 2.25 KiB {1} [built]
       | ./packages/web/src/index.js 202 bytes [built]
       | ./packages/web/src/Connection.js 774 bytes [built]
       | ./packages/web/src/EventWatcher.js 1.13 KiB [built]
       |     + 1 hidden module
  [11] multi react react-dom react-router react-hot-loader 64 bytes {0} [built]
  [12] (webpack)/buildin/harmony-module.js 597 bytes {1} [built]
  [13] multi ./packages/web/src/index.js 28 bytes {1} [built]
    + 10 hidden modules

ERROR in ./packages/web/src/Connection.js
Module not found: Error: Can't resolve '@nameless/common' in '/Users/Zach/nameless/packages/web/src'
 @ ./packages/web/src/Connection.js 3:0-57 16:76-97
 @ ./packages/web/src/index.js
 @ multi ./packages/web/src/index.js

ERROR in multi react react-dom react-router react-hot-loader
Module not found: Error: Can't resolve 'react-dom' in '/Users/Zach/nameless'
 @ multi react react-dom react-router react-hot-loader

ERROR in ./packages/web/src/index.js
Module not found: Error: Can't resolve 'react-dom' in '/Users/Zach/nameless/packages/web/src'
 @ ./packages/web/src/index.js 5:0-33 7:0-8
 @ multi ./packages/web/src/index.js

ERROR in multi react react-dom react-router react-hot-loader
Module not found: Error: Can't resolve 'react-router' in '/Users/Zach/nameless'
 @ multi react react-dom react-router react-hot-loader
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./packages/web/index.html 637 bytes {0} [built]

    at Promise.all.then.arr (/Users/Zach/nameless/node_modules/lerna/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  code: 2,
  killed: false,
  stdout: '\n> @ build-web /Users/Zach/nameless\n> NODE_ENV=production webpack --config packages/web/webpack.config.babel.js\n\nHash: f69af62842e3eb180b09\nVersion: webpack 4.4.1\nTime: 1859ms\nBuilt at: 2018-3-31 11:56:49\n 4 assets\nEntrypoint index = index.js index.map\nEntrypoint react = react.js react.map\n  [10] ./packages/web/src/index.js + 3 modules 2.25 KiB {1} [built]\n       | ./packages/web/src/index.js 202 bytes [built]\n       | ./packages/web/src/Connection.js 774 bytes [built]\n       | ./packages/web/src/EventWatcher.js 1.13 KiB [built]\n       |     + 1 hidden module\n  [11] multi react react-dom react-router react-hot-loader 64 bytes {0} [built]\n  [12] (webpack)/buildin/harmony-module.js 597 bytes {1} [built]\n  [13] multi ./packages/web/src/index.js 28 bytes {1} [built]\n    + 10 hidden modules\n\nERROR in ./packages/web/src/Connection.js\nModule not found: Error: Can\'t resolve \'@nameless/common\' in \'/Users/Zach/nameless/packages/web/src\'\n @ ./packages/web/src/Connection.js 3:0-57 16:76-97\n @ ./packages/web/src/index.js\n @ multi ./packages/web/src/index.js\n\nERROR in multi react react-dom react-router react-hot-loader\nModule not found: Error: Can\'t resolve \'react-dom\' in \'/Users/Zach/nameless\'\n @ multi react react-dom react-router react-hot-loader\n\nERROR in ./packages/web/src/index.js\nModule not found: Error: Can\'t resolve \'react-dom\' in \'/Users/Zach/nameless/packages/web/src\'\n @ ./packages/web/src/index.js 5:0-33 7:0-8\n @ multi ./packages/web/src/index.js\n\nERROR in multi react react-dom react-router react-hot-loader\nModule not found: Error: Can\'t resolve \'react-router\' in \'/Users/Zach/nameless\'\n @ multi react react-dom react-router react-hot-loader\nChild html-webpack-plugin for "index.html":\n     1 asset\n    Entrypoint undefined = index.html\n       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./packages/web/index.html 637 bytes {0} [built]\n',
  stderr: 'npm ERR! code ELIFECYCLE\nnpm ERR! errno 2\nnpm ERR! @ build-web: `NODE_ENV=production webpack --config packages/web/webpack.config.babel.js`\nnpm ERR! Exit status 2\nnpm ERR! \nnpm ERR! Failed at the @ build-web script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/Zach/.npm/_logs/2018-03-31T15_56_50_209Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'DIRNAME=$(pwd | grep -Po "[^/]+$") && cd .. && npm run build-$DIRNAME',
  timedOut: false,
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build-all: `lerna exec --parallel --stream -- 'DIRNAME=$(pwd | grep -Po "[^/]+$") && cd .. && npm run build-$DIRNAME'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Zach/.npm/_logs/2018-03-31T15_56_50_354Z-debug.log
```

**Comment by Slowki** [comment]
[npx lerna bootstrap](https://lernajs.io/#command-bootstrap) should fix that.
